services:

  keycloak-postgres:
    image: postgres:18.6
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U keycloak -d keycloak'"]
      interval: 3s
      timeout: 2s
      retries: 10


  keycloak:
    image: quay.io/keycloak/keycloak:26.7.3
    command: ["start-dev"]
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    environment:   
      KC_BOOTSTRAP_ADMIN_USERNAME: admin 
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: http://keycloak:8080
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_HOSTNAME_DEBUG: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    expose:
      - 8080
    ports:
      - 8080:8080

  mailhog:
    image: mailhog/mailhog:v1.0.1
    expose:
      - 1025
      - 8025
    ports:
      - 1025:1025
      - 8025:8025

  lldap:
    image: lldap/lldap:stable
    ports:
      - 17170:17170
    environment:
      - LLDAP_JWT_SECRET=xxx
      - LLDAP_KEY_SEED=xxx
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
      - LLDAP_LDAP_USER_PASS=password
  

  employees-postgres:
    image: postgres:18.6
    profiles:
      - app
    environment:
      POSTGRES_USER: employees
      POSTGRES_PASSWORD: employees
      POSTGRES_DB: employees
    expose:
      - 5432
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U employees -d employees'"]
      interval: 3s
      timeout: 2s
      retries: 10

  employees-backend:
    image: training360/keycloak-employees:2.0.0
    profiles:
      - app
    depends_on:
      employees-postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://employees-postgres:5432/employees
      SPRING_DATASOURCE_USERNAME: employees
      SPRING_DATASOURCE_PASSWORD: employees
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/employees
    expose:
      - 8080
    ports:
      - 8081:8080

  employees-frontend:
    image: training360/keycloak-employees-ui:2.0.0
    profiles:
      - app
    depends_on:
      - employees-backend
    environment:
      SERVER_PORT: 8080
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/employees
      EMPLOYEES_BACKEND_URL: http://employees-backend:8080
    expose:
      - 8080
    ports:
      - 8082:8080

